### ISSUE TITLE
Posts pushed to slave site have time set in future after WP4.4 upgrade.

### ISSUE THREAD

**Issue by bcarney66** [confuzzledduck/syndicate-out#35]
I run a master site with 27 slave sites.  With today's WordPress 4.4 update, posts are being pushed to sites, but they have a time set 5 hours in the future so they show up as a scheduled post.   (I'm in the Eastern (US) Time Zone, which is 5 hours different from GMT/UTC at this time of year if that matters).

It used to be immediate, which is what I need for my project.

**Comment by confuzzledduck** [comment]
That's interesting. Thanks for letting me know. I plan to do some work on the plugin over the next few weeks, so I'll take a look at this one.

Just to confirm -- all of the sites you're using have the same timezone set in WP (Eastern US)?

**Comment by bcarney66** [comment]
Yes, all my sites are set to be in the Eastern Time zone.  The issue may be with Wordpress and not the plugin - please see:

https://core.trac.wordpress.org/ticket/35053

https://core.trac.wordpress.org/changeset/34681

**Comment by confuzzledduck** [comment]
Good spot. I might have a play with the plugin to see if I can work around it until it's patched, but I don't want to do anything which would effect it in the future. I'll see what timezone / options there are which might help.

**Comment by confuzzledduck** [comment]
After much debate this issue is fixed (reverted to pre-4.4 behaviour) as of 4.4.1. I will keep an eye on the other issues coming out of it.

For now I'll close this ticket. Thanks for reporting it and the investigative work!
