### ISSUE TITLE
get the blog posts remote from an another web xml rpc

### ISSUE THREAD

**Issue by saswe** [confuzzledduck/syndicate-out#37]
Hello
Is it possible to get the blog posts via syndicate-out remote from an another web
Some blog portals have no function for backup or pluggin or run code.
The sides are completely locked to write blog via web or XML RPC apps
This could be a good tool to move the blog and pictures to another website.

If you have a solution to this, I am sponsoring you

SINCERELY
Stefan

**Comment by confuzzledduck** [comment]
I'm afraid this plugin is designed to work the other way around -- to transmit **from** one site to another, rather than to pull posts from a remote site. There wouldn't be a way to modify this plugin to do as you require. Sorry!
